# Generated by Django 5.2 on 2025-04-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='email',
        ),
        migrations.RemoveField(
            model_name='team',
            name='login',
        ),
    ]
