# Generated by Django 5.2 on 2025-04-15 11:22

import teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_remove_team_email_remove_team_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='banners/', validators=[teams.models.validate_banner_file]),
        ),
    ]
