# Generated by Django 5.2 on 2025-05-02 14:27

import django.db.models.deletion
import teams.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_alter_team_banner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='banners/', validators=[teams.models.validate_banner_file], verbose_name='Баннер'),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captained_teams', to=settings.AUTH_USER_MODEL, verbose_name='Капитан'),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='Участники команды'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(error_messages={'unique': 'Команда с таким названием уже существует.'}, max_length=255, unique=True, verbose_name='Название'),
        ),
    ]
