# Generated by Django 5.2 on 2025-05-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_avatar_user_birthday_user_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
