# Generated by Django 5.2 on 2025-05-19 23:56

from django.db import migrations
from django.db import connection


def remove_contacts_column(apps, schema_editor):
    # Check if the column exists before trying to remove it
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'accounts_user' AND column_name = 'contacts';
        """)
        if cursor.fetchone():
            cursor.execute('ALTER TABLE accounts_user DROP COLUMN IF EXISTS contacts;')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_education'),
    ]

    operations = [
        migrations.RunPython(remove_contacts_column, migrations.RunPython.noop),
    ]
