# Generated by Django 5.2 on 2025-05-19 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20250520_0256'),
    ]

    operations = [
    ]
